### PR TITLE
Fix compilation after changes to trait and run

### PR DESCRIPTION
**Pull request by celinval**
The following PRs needed to be addressed:
  - https://github.com/rust-lang/rust/pull/119833
  - https://github.com/rust-lang/rust/pull/119790

r? @oli-obk

### CODE REVIEW

**Comment by celinval** [comment]
@oli-obk, I need your github approval so I can merge this.

**Review by oli-obk — APPROVED** [review]

**Comment by celinval** [comment]
Thanks!

**Pull request merged**
