### PR TITLE
Add a developer documentation to our book

### PR DESCRIPTION
**Pull request by celinval**
Add a few notes on how to run tests. @ouz-a can you please review too?

### CODE REVIEW

**Comment by ouz-a** [comment]
This looks very good to me overall; however, I would very much appreciate if you put a brief section dedicated to running this under custom toolchain, i.e which part of what scripts we should change in order to run this under custom toolchain, here's why I'm suggesting this: For creating less friction for the developer, as I tried to use this test suite as debugging tool to run test against, I couldn't figure out what settings to change, so I ended up hacking together version of `crate-info.rs` that runs the tests 😅

**Comment by celinval** [comment]
@ouz-a Done

**Comment by ouz-a** [comment]
LGTM!

**Review by oli-obk — APPROVED** [review]
Very thorough docs, thanks!

**Pull request merged**
